#!/bin/bash
# overnight_reshape.sh — decode-time distribution repair: can we unfreeze the mid-price at
# 10-step cost WITHOUT retraining and WITHOUT touching the sampler?
#
# ── WHERE EVERY PRIOR LEVER LANDED ────────────────────────────────────────────────────────────
#   CFG (guidance)        ✗  reshapes the conditional MEAN; adds no variance
#   --depth-temp (linear) ✗  cliff — linearly sliding a collapsed spike crosses all-at-once
#   HYBRID / CHURN        ✗  cliff + numerically unstable on the unclamped ckpt (cond_z ±1400)
#   unclamp retrain       ◐  fixed the SIGN axis (neg-depth decodes x11; DDPM B-share 35→40%)
#                            but NOT the MAGNITUDE axis: DDIM10 B_crossing_limit stayed 0 —
#                            deterministic sampling still collapses depth's variance, so the
#                            negative excursions are too small to exceed the spread.
#
# ── TONIGHT'S TWO NEW MECHANISMS (both decode-time only; sampler & weights untouched) ────────
#   --depth-reshape   Quantile match: rank each raw z within the model's OWN recent outputs
#                     (rolling buffer, midrank ties), read that quantile off the REAL signed-depth
#                     marginal. Nonlinear per-sample map — uses the continuous intra-spike
#                     variation as rank, so the bottom ~0.9% of ranks land on genuine -1..-10-tick
#                     crossing depths with REAL magnitudes. Fail-safe: a fully-degenerate source
#                     maps to the target's MEDIAN, not an extreme (unlike depth-temp's cliff).
#   --depth-noise σ   The dumb comparator: per-sample N(0,σ) on z_depth at decode, LIMIT only.
#                     Can split the atom (per-sample), cannot destabilize (never enters the
#                     sampler or conditioning). σ=0.15 predicts ~0.5% crossing vs real 0.91%.
#   --size-reshape    Same quantile mechanism for size, per decoded type. Bonus: kills the
#                     30-40% negative-size decode waste (42% of DDPM batches were resampled).
#
# WHAT DECIDES SUCCESS in each summary.md block:
#   B_crossing_limit > 0            (Channel B alive — the thing NOTHING else has achieved on DDIM)
#   unique mid-prices → tens        (real session = 69; frozen = 6-17; diverging = 100-160)
#   DIAG reshape: applied counts    (mechanism actually engaged)
#   cond_z[depth] min/max sane      (no CHURN-style ±1400 blowup)
#
# Usage:  bash scripts/overnight_reshape.sh          # everything, ~4-5h
#         bash scripts/overnight_reshape.sh --id 0.635 --real <csv>

set -uo pipefail
TICKER="INTC"; DATE="20150130"; ST="09:30:00"; ET="10:00:00"
ID="0.635"                                   # the unclamped-retrain checkpoint
REAL="ABIDES/log/market_replay_${TICKER}_2015-01-30_10-00-00_30/processed_orders.csv"
OUT_DIR="overnight_reshape/$(date +%Y%m%d_%H%M%S)"
while [[ $# -gt 0 ]]; do case "$1" in
  --id) ID="$2"; shift 2;; --real) REAL="$2"; shift 2;;
  --out-dir) OUT_DIR="$2"; shift 2;;
  *) echo "unknown arg: $1" >&2; exit 1;; esac; done
mkdir -p "$OUT_DIR/logs"; SUM="$OUT_DIR/summary.md"
echo "# Reshape night — $(date '+%F %T')  ckpt=$ID" > "$SUM"; echo "" >> "$SUM"

# ── Stage 0: preflight ────────────────────────────────────────────────────────────────────────
if pgrep -f "main.py" > /dev/null; then
  echo "!! training (main.py) still running — kill it first (GPU contention turned a 45min run"
  echo "   into 3.5h last time). Refusing to start."; exit 1
fi

# Evaluating the UNCLAMPED checkpoint → conditioning must match training. File flag, not env
# (env vars silently failed twice on this remote).
touch UNCLAMP_DEPTH_FLAG
echo "UNCLAMP_DEPTH_FLAG set (ckpt $ID is unclamp-trained; conditioning must match)"

# Real quantile targets (CPU-only, ~minutes). Built from the SAME preprocess_data pipeline as
# training — includes the pre-event-snapshot indexing fix, so signed depths are genuine.
if [[ ! -f data/quantile_targets/real_depth_limit.npy ]]; then
  echo "── building real-data quantile targets ──"
  python scripts/build_quantile_targets.py 2>&1 | tee "$OUT_DIR/logs/build_targets.txt" \
    || { echo "target build FAILED — reshape cells cannot run"; exit 1; }
fi

# Real market-replay CSV for flow_mix (crashed on every run last night — file missing on scratch).
# Regenerated by the same config in pure-replay mode (no -d flag → no model, CPU, ~10-20 min).
if [[ ! -f "$REAL" ]]; then
  echo "── regenerating real market-replay CSV (missing: $REAL) ──"
  python ABIDES/abides.py -c world_agent_sim -t "$TICKER" -date "$DATE" -st "$ST" -et "$ET" \
    > "$OUT_DIR/logs/market_replay.txt" 2>&1
  [[ -f "$REAL" ]] || echo "WARNING: replay finished but $REAL still missing — flow_mix will run gen-only"
fi

run () { # run <tag> <type> <nsteps> <extra>
  local TAG="$1" TYPE="$2" NS="$3" EXTRA="$4"
  local LOG="$OUT_DIR/logs/${TAG}.txt"; local DONE="$OUT_DIR/logs/.done_${TAG}"
  [[ -f "$DONE" ]] && { echo "  SKIP $TAG"; return; }
  echo "── $TAG"
  local S; S=$(mktemp); touch "$S"; local T0; T0=$(date +%s)
  local A=(python ABIDES/abides.py -c world_agent_sim -t "$TICKER" -date "$DATE" -st "$ST" -et "$ET"
           -d True -m TRADES -type "$TYPE" -nsteps "$NS" -eta 0.0 -id "$ID")
  # shellcheck disable=SC2206
  [[ -n "$EXTRA" ]] && A+=($EXTRA)
  echo "   ${A[*]}"
  if ! "${A[@]}" > "$LOG" 2>&1; then echo "  ERROR — see $LOG"; echo "## $TAG — ERROR" >> "$SUM"; rm -f "$S"; return; fi
  local SECS=$(( $(date +%s) - T0 ))
  local CSV; CSV=$(find ABIDES/log -name processed_orders.csv -newer "$S" ! -path "*/paper/*" ! -path "*market_replay*" 2>/dev/null | sort | tail -1); rm -f "$S"
  { echo "## $TAG  (${SECS}s)"; echo '```'
    grep "checkpoint used" "$LOG" | tail -1
    if [[ -n "$CSV" && -f "$REAL" ]]; then python -m evaluation.quantitative_eval.flow_mix --real "$REAL" --gen "$CSV" 2>&1
    elif [[ -n "$CSV" ]]; then python -m evaluation.quantitative_eval.flow_mix --gen "$CSV" 2>&1; fi
    echo ""; sed -n '/=== WORLDAGENT DIAGNOSTICS ===/,/=== END DIAGNOSTICS ===/p' "$LOG"
    echo '```'; echo ""; } >> "$SUM"
  touch "$DONE"; echo "  done ${SECS}s"
}

echo "════ STAGE 1: the headline — quantile depth reshape on the frozen sampler ════"
run "DDIM10_dr"          DDIM 10 "--depth-reshape"
run "DDIM10_dr_sr"       DDIM 10 "--depth-reshape --size-reshape"
# Channel A regressed on ckpt 0.635 (market decode 0.78% vs real 2.8%); prior decode restores it.
# This cell = the full fast-sampler candidate: both channels repaired at 10-step cost.
run "DDIM10_dr_sr_prior" DDIM 10 "--depth-reshape --size-reshape --type-decode prior"

echo "════ STAGE 2: the dumb-variance comparator — is smart reshaping even needed? ════"
run "DDIM10_dn0.15"      DDIM 10 "--depth-noise 0.15"
run "DDIM10_dn0.3"       DDIM 10 "--depth-noise 0.3"

echo "════ STAGE 3: generality — other backbone, isolation, healthy-sampler control ════"
run "DPMpp10_dr_sr"      DPM_SOLVER_PP 10 "--depth-reshape --size-reshape"
run "DDIM10_sr"          DDIM 10 "--size-reshape"                     # size axis alone
# Control: reshape on the WORKING sampler. Tests (a) no harm, (b) whether it corrects DDPM's
# known depth-too-deep bias (LOB-Bench: median 4 ticks vs real 1). Slowest — runs last.
run "DDPM100_dr_sr"      DDPM 100 "--depth-reshape --size-reshape"

echo ""; echo "══════════════════════════════════════════"
echo "  Done. Summary: $SUM"
echo "══════════════════════════════════════════"
echo "READ, per block:  B_crossing_limit (>0 = Channel B alive — nothing else has achieved this"
echo "  on DDIM), unique mids (target ~69, frozen <20, diverging >100), DIAG reshape applied"
echo "  counts, and cond_z[depth] min/max staying sane (no CHURN-style blowup)."
echo "  dr vs dn cells: does the distribution-aware map beat plain per-sample noise?"
